title: Runaways
subtitle: A Subaltern History of Bahamian Slave Resistance 
author:
  name: Wax user
  email: your-email@domain.com
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  minicomp: # name of collection
    output: true # makes sure pages are output as html files
    layout: "minicomp_item" # the layout for the pages to use
    metadata:
      source: "minicomp.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/minicomp" # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      minicomp:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - publisher
          - publication_date
          - advertisement_date
          - names_mentioned
          - runaway_origin
          - runaway_destination
          - enslaved_gender
          - physical
          - enslaved_occupation
          - enslaved_age

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: "Sip-Sip"
    sub:
      - label: "Marronage"
        link: "/exhibits/marronage/"
      - label: "Bahamian Slavery"
        link: "/exhibits/bahamian-slavery/"
      - label: "Subset Collection"
        link: "/exhibits/subset/"
  - label: "Browse"
    link: "/collection/"
  - label: "Search"
    link: "/search/"
  - label: "Creator"
    link: "/creator/"
